"""导出浏览器Cookie到文件"""
import browser_cookie3
import sys
import os

def export_cookies(domain='youtube.com', output_file='cookies.txt'):
    """导出浏览器Cookie到Netscape格式文件"""
    try:
        # 尝试获取Chrome cookie
        cj = browser_cookie3.chrome(domain_name=domain)
    except Exception as e:
        print(f"Chrome cookie failed: {e}")
        try:
            cj = browser_cookie3.edge(domain_name=domain)
            browser_name = "Edge"
        except:
            print("Failed to get cookies from any browser")
            sys.exit(1)
    else:
        browser_name = "Chrome"

    # 写入Netscape格式cookie文件
    with open(output_file, 'w') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# This file was generated by browser-cookie3\n\n')
        for cookie in cj:
            # 写入cookie（格式：domain, flag, path, secure, expiration, name, value）
            f.write(f'{cookie.domain}\t')
            f.write('TRUE\t' if cookie.domain.startswith('.') else 'FALSE\t')
            f.write(f'{cookie.path}\t')
            f.write('TRUE\t' if cookie.secure else 'FALSE\t')
            f.write(f'{int(cookie.expires) if cookie.expires else 0}\t')
            f.write(f'{cookie.name}\t')
            f.write(f'{cookie.value}\n')

    print(f"[OK] Cookie exported to {output_file} ({browser_name})")
    print(f"    Found {len(list(cj))} cookies for {domain}")

if __name__ == '__main__':
    domain = sys.argv[1] if len(sys.argv) > 1 else 'youtube.com'
    output = sys.argv[2] if len(sys.argv) > 2 else 'cookies.txt'
    export_cookies(domain, output)
